* # RU102N [[Redis]] for .NET Developers

## Section 1
* *Link:* https://university.redis.com/courses/ru102n/
* ### 1.1 - .NET Client Ecosystem Overview
* There are different levels of abstraction that Redis clients can provide to users. It's helpful if we try to group those together for a conversation about Redis clients. Let's think of them in these groups:
* 1. Minimal Protocol Clients: These clients basically handle connection, wrap the RESP protocol (the wire protocol for Redis) and little else. They're quite minimalist and intended to provide maximum control to the user.
2. General Command Level Clients: The clients that directly expose the Redis command interface and provide some parsing for the result structures bubbling up from it. These have a more or less 1:1 mapping between commands in Redis and commands in the client.
3. Higher Level Abstract Clients: These clients are intended more to provide a friendly user interface to developers and provide some meaningful abstraction above the Redis command interface and paradigms the users are used to.
4. Framework Integrations: These clients are written to interact directly with a particular framework, often times they implement some very particular functionality in a way native to the framework.
* *StackExchange.Redis* falls somewhere between the second and third tier clients, while also leaving open a more or less minimalist ad-hoc API that we'll explore in later sections. It's best described as that second-tier General Command Level Client of Redis.
* All of the other third and fourth level libraries we'll be looking at later in this course have this Library as a dependency.
* ### 1.2 - Getting Started with StackExchange.Redis
* ''